puts "Seeding CarModel data..."

CarModel.create([
  { database_name: "ford_aspire" },
  { database_name: "ford_ecosport" },
  { database_name: "ford_endeavour" },
  { database_name: "ford_figo" },
  { database_name: "honda_amaze" },
  { database_name: "honda_city" },
  { database_name: "honda_wr_v" },
  { database_name: "hyundai_aura" },
  { database_name: "hyundai_grand_i10" },
  { database_name: "hyundai_i10" },
  { database_name: "jeep_compass" },
  { database_name: "jeep_meridian" },
  { database_name: "kia_carens" },
  { database_name: "kia_seltos" },
  { database_name: "kia_sonet" },
  { database_name: "land_rover_defender" },
  { database_name: "mahindra_scorpio" },
  { database_name: "mahindra_thar" },
  { database_name: "mahindra_xuv300" },
  { database_name: "mahindra_xuv400" },
  { database_name: "mahindra_xuv700" },
  { database_name: "maruti_celerio" },
  { database_name: "maruti_suzuki_brezza" },
  { database_name: "maruti_suzuki_s_presso" },
  { database_name: "maruti_suzuki_swift" },
  { database_name: "maruti_suzuki_wagonr" },
  { database_name: "maruti_suzuki_xl6" },
  { database_name: "mg_astor" },
  { database_name: "mg_gloster" },
  { database_name: "mg_hector" },
  { database_name: "mg_zs_ev" },
  { database_name: "renault_kiger" },
  { database_name: "renault_triber" },
  { database_name: "skoda_kushaq" },
  { database_name: "skoda_slavia" },
  { database_name: "tata_harrier" },
  { database_name: "tata_punch" },
  { database_name: "tata_tiago" },
  { database_name: "toyota_camry" },
  { database_name: "toyota_fortuner" },
  { database_name: "toyota_fortuner_legender" },
  { database_name: "toyota_glanza" },
  { database_name: "toyota_innova_crysta" }
])


puts "CarModel data seeded successfully!"